[package]
name = "sludge"
version = "0.1.0"
authors = ["Sean Leffler <sean@errno.com>"]
edition = "2018"

[dependencies]
rlua = { path = "../rlua" }
nalgebra = "0.22.0"
ncollide2d = "0.24.0"
hecs = { path = "../hecs" }
generational-arena = "0.2.8"
derivative = "2.1.1"
anyhow = "1.0.32"
crossbeam-channel = "0.4.4"
fern = { version = "0.6.0", features = ["colored"] }
log = "0.4.11"
chrono = "0.4.15"
hibitset = "0.6.3"
hashbrown = "0.9.0"
shrev = "1.1.1"
atomic_refcell = "0.1.6"
thread_local = "1.0.1"
lazy_static = "1.4.0"

[dev-dependencies]
approx = "0.3.2"
