[package]
name = "sludge-macros"
version = "0.1.0"
authors = ["Sean Leffler <sean@errno.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"